set List=DUB KIR LCY LON ABZ BHX BRS CWL DSA EMA EDI GLA IOM JER LBA LPL LGW LHR MAN NCL NQY MEL PER SYD VIE BAH BRU BOJ YYC YEG YHZ YUL YOW YQB YQR YXE YYT YYZ YVR YYJ YWG DBV PUY PUB PRG CPH BOD LYS MRS MPL NTE NCE CDG PGF RNS TLS TXL DUS FRA HAM MUC STR ATH CFU BUD BLQ CTA MIL LIN MXP NAP PSA FCO VCE VRN AGA NDS AMS MCT WAW FAO LIS ALC BCN BIO FUE LPA ACE MAD AGP MJV PMI SCQ TFS AND GVA ZRH ADB BOS ORD BDL

for %%a in (%list%) do (

start C:\Users\Artur\AppData\Local\Programs\Python\Python35-32\python.exe C:\Users\Artur\Desktop\current\SeleniumScraper\SeleniumScraper\SeleniumScraper.py %%a
)